import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * 舊版銷管 API（第 2 階段）的資料庫準備：
 *
 * 1. legacy_crm 業務表的文字欄改用 "C" 排序（逐位元組），與 isin_vb6 的 SQLite 相同。
 *    頭筆～尾筆依單號文字順序移動、代碼區間與前綴查詢都依此順序，索引也才能直接用在 ORDER BY。
 *    只改排序規則，型別與長度不變；索引會重建。
 * 2. 建立 `crm` 功能（features），舊版銷管以它控管讀寫權限；admin 不需授權即可使用。
 */
export class PrepareLegacyCrmApi1791460000000 implements MigrationInterface {
  name = 'PrepareLegacyCrmApi1791460000000';

  private readonly collate = [
    `ALTER TABLE "legacy_crm"."banks"
          ALTER COLUMN "code" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "short_name" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "full_name" TYPE character varying(30) COLLATE "C",
          ALTER COLUMN "contact" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "phone1" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "phone2" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "address" TYPE character varying(60) COLLATE "C",
          ALTER COLUMN "legacy_bono" TYPE character varying(30) COLLATE "C",
          ALTER COLUMN "legacy_boname" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "account_no" TYPE character varying(8) COLLATE "C",
          ALTER COLUMN "account_name" TYPE character varying(30) COLLATE "C",
          ALTER COLUMN "notes" TYPE character varying(40) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."drawing_group_items"
          ALTER COLUMN "group_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "customer_code" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "drawing_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "customer_drawing_no" TYPE character varying(40) COLLATE "C",
          ALTER COLUMN "material" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "thickness" TYPE character varying(6) COLLATE "C",
          ALTER COLUMN "is_laser" TYPE character varying(2) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."drawing_groups"
          ALTER COLUMN "group_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "created_date_raw" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "customer_code" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "customer_name" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "customer_drawing_no" TYPE character varying(40) COLLATE "C",
          ALTER COLUMN "notes" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "legacy_xx" TYPE character varying(1) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."materials"
          ALTER COLUMN "material" TYPE character varying(50) COLLATE "C",
          ALTER COLUMN "thickness" TYPE character varying(30) COLLATE "C",
          ALTER COLUMN "product_name" TYPE character varying(100) COLLATE "C",
          ALTER COLUMN "category" TYPE character varying(50) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."order_documents"
          ALTER COLUMN "order_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "order_date_raw" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "delivery_date_raw" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "customer_code" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "customer_name" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "actor_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "actor_name" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "payment_method" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "delivery_method" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "note" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "note2" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "closed" TYPE character varying(2) COLLATE "C",
          ALTER COLUMN "legacy_xx" TYPE character varying(1) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."order_items"
          ALTER COLUMN "order_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "legacy_sn" TYPE character varying(2) COLLATE "C",
          ALTER COLUMN "legacy_date_r_raw" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "legacy_date_e_raw" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "legacy_factor_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "legacy_factor" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "legacy_d_dwgok" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "drawing_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "customer_model" TYPE character varying(40) COLLATE "C",
          ALTER COLUMN "material" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "thickness" TYPE character varying(4) COLLATE "C",
          ALTER COLUMN "outsource" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "source" TYPE character varying(4) COLLATE "C",
          ALTER COLUMN "post_process" TYPE character varying(50) COLLATE "C",
          ALTER COLUMN "unit" TYPE character varying(4) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."partners"
          ALTER COLUMN "kind" TYPE character varying(8) COLLATE "C",
          ALTER COLUMN "code" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "full_name" TYPE character varying(100) COLLATE "C",
          ALTER COLUMN "short_name" TYPE character varying(50) COLLATE "C",
          ALTER COLUMN "responsible" TYPE character varying(50) COLLATE "C",
          ALTER COLUMN "phone1" TYPE character varying(40) COLLATE "C",
          ALTER COLUMN "phone2" TYPE character varying(40) COLLATE "C",
          ALTER COLUMN "fax" TYPE character varying(40) COLLATE "C",
          ALTER COLUMN "tax_id" TYPE character varying(30) COLLATE "C",
          ALTER COLUMN "postal_code" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "address" TYPE character varying(250) COLLATE "C",
          ALTER COLUMN "shipping_address" TYPE character varying(250) COLLATE "C",
          ALTER COLUMN "invoice_title" TYPE character varying(100) COLLATE "C",
          ALTER COLUMN "invoice_tax_id" TYPE character varying(30) COLLATE "C",
          ALTER COLUMN "bank_name" TYPE character varying(100) COLLATE "C",
          ALTER COLUMN "bank_account" TYPE character varying(100) COLLATE "C",
          ALTER COLUMN "contact1" TYPE character varying(50) COLLATE "C",
          ALTER COLUMN "contact2" TYPE character varying(50) COLLATE "C",
          ALTER COLUMN "contact3" TYPE character varying(50) COLLATE "C",
          ALTER COLUMN "start_date_raw" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "latest_transaction_date_raw" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "email" TYPE character varying(150) COLLATE "C",
          ALTER COLUMN "dxf_path" TYPE character varying(250) COLLATE "C",
          ALTER COLUMN "main_product" TYPE character varying(100) COLLATE "C",
          ALTER COLUMN "notes" TYPE character varying(2000) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."parts"
          ALTER COLUMN "drawing_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "drawing_name" TYPE character varying(30) COLLATE "C",
          ALTER COLUMN "drawing_ref" TYPE character varying(40) COLLATE "C",
          ALTER COLUMN "customer_code" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "customer_model" TYPE character varying(40) COLLATE "C",
          ALTER COLUMN "material" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "thickness" TYPE character varying(4) COLLATE "C",
          ALTER COLUMN "unit" TYPE character varying(2) COLLATE "C",
          ALTER COLUMN "actor_no" TYPE character varying(6) COLLATE "C",
          ALTER COLUMN "actor" TYPE character varying(8) COLLATE "C",
          ALTER COLUMN "drawing_date_raw" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "directory_path" TYPE character varying(50) COLLATE "C",
          ALTER COLUMN "cnc1" TYPE character varying(30) COLLATE "C",
          ALTER COLUMN "cnc2" TYPE character varying(30) COLLATE "C",
          ALTER COLUMN "cnc3" TYPE character varying(12) COLLATE "C",
          ALTER COLUMN "cnc4" TYPE character varying(12) COLLATE "C",
          ALTER COLUMN "cnc5" TYPE character varying(50) COLLATE "C",
          ALTER COLUMN "notes" TYPE character varying(50) COLLATE "C",
          ALTER COLUMN "yy" TYPE character varying(1) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."phrases"
          ALTER COLUMN "phrase_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "content" TYPE character varying(250) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."postal_codes"
          ALTER COLUMN "postal_code" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "region_name" TYPE character varying(100) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."quote_documents"
          ALTER COLUMN "quote_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "quote_date_raw" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "customer_code" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "customer_name" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "actor_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "actor_name" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "attention" TYPE character varying(40) COLLATE "C",
          ALTER COLUMN "legacy_xx" TYPE character varying(1) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."quote_items"
          ALTER COLUMN "quote_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "customer_model" TYPE character varying(40) COLLATE "C",
          ALTER COLUMN "material" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "thickness" TYPE character varying(6) COLLATE "C",
          ALTER COLUMN "summary" TYPE character varying(250) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."quote_note_lines"
          ALTER COLUMN "quote_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "note" TYPE character varying(250) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."receipt_allocation_lines"
          ALTER COLUMN "receipt_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "sale_no" TYPE character varying(10) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."receipt_documents"
          ALTER COLUMN "receipt_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "receipt_date_raw" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "closing_date_raw" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "customer_code" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "customer_name" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "actor_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "actor_name" TYPE character varying(10) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."receipt_payment_lines"
          ALTER COLUMN "receipt_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "category" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "check_number" TYPE character varying(30) COLLATE "C",
          ALTER COLUMN "check_date_raw" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "bank_account" TYPE character varying(30) COLLATE "C",
          ALTER COLUMN "collect_agent" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "bank_short_name" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "note" TYPE character varying(40) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."sales_documents"
          ALTER COLUMN "sale_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "sale_date_raw" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "legacy_date_e_raw" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "customer_code" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "customer_name" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "actor_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "actor_name" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "linked_order_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "payment_method" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "delivery_method" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "invoice_number" TYPE character varying(30) COLLATE "C",
          ALTER COLUMN "shipping_address" TYPE character varying(60) COLLATE "C",
          ALTER COLUMN "note" TYPE character varying(50) COLLATE "C",
          ALTER COLUMN "tax_mode" TYPE character varying(10) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."sales_items"
          ALTER COLUMN "sale_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "legacy_sn" TYPE character varying(2) COLLATE "C",
          ALTER COLUMN "legacy_date_r_raw" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "legacy_factor_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "legacy_factor" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "drawing_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "customer_model" TYPE character varying(40) COLLATE "C",
          ALTER COLUMN "material" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "thickness" TYPE character varying(6) COLLATE "C",
          ALTER COLUMN "outsource" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "unit" TYPE character varying(4) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."work_documents"
          ALTER COLUMN "work_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "transfer_date_raw" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "customer_code" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "customer_name" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "actor_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "actor_name" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "order_no" TYPE character varying(10) COLLATE "C"`,
    `ALTER TABLE "legacy_crm"."work_items"
          ALTER COLUMN "work_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "drawing_no" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "material" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "thickness" TYPE character varying(6) COLLATE "C",
          ALTER COLUMN "outsource" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "cnc_ok" TYPE character varying(10) COLLATE "C",
          ALTER COLUMN "plating_work" TYPE character varying(20) COLLATE "C",
          ALTER COLUMN "post_process" TYPE character varying(50) COLLATE "C",
          ALTER COLUMN "order_no" TYPE character varying(10) COLLATE "C"`,
  ];

  private readonly restore = [
    `ALTER TABLE "legacy_crm"."banks"
          ALTER COLUMN "code" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "short_name" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "full_name" TYPE character varying(30) COLLATE "default",
          ALTER COLUMN "contact" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "phone1" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "phone2" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "address" TYPE character varying(60) COLLATE "default",
          ALTER COLUMN "legacy_bono" TYPE character varying(30) COLLATE "default",
          ALTER COLUMN "legacy_boname" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "account_no" TYPE character varying(8) COLLATE "default",
          ALTER COLUMN "account_name" TYPE character varying(30) COLLATE "default",
          ALTER COLUMN "notes" TYPE character varying(40) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."drawing_group_items"
          ALTER COLUMN "group_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "customer_code" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "drawing_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "customer_drawing_no" TYPE character varying(40) COLLATE "default",
          ALTER COLUMN "material" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "thickness" TYPE character varying(6) COLLATE "default",
          ALTER COLUMN "is_laser" TYPE character varying(2) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."drawing_groups"
          ALTER COLUMN "group_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "created_date_raw" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "customer_code" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "customer_name" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "customer_drawing_no" TYPE character varying(40) COLLATE "default",
          ALTER COLUMN "notes" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "legacy_xx" TYPE character varying(1) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."materials"
          ALTER COLUMN "material" TYPE character varying(50) COLLATE "default",
          ALTER COLUMN "thickness" TYPE character varying(30) COLLATE "default",
          ALTER COLUMN "product_name" TYPE character varying(100) COLLATE "default",
          ALTER COLUMN "category" TYPE character varying(50) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."order_documents"
          ALTER COLUMN "order_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "order_date_raw" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "delivery_date_raw" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "customer_code" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "customer_name" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "actor_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "actor_name" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "payment_method" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "delivery_method" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "note" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "note2" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "closed" TYPE character varying(2) COLLATE "default",
          ALTER COLUMN "legacy_xx" TYPE character varying(1) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."order_items"
          ALTER COLUMN "order_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "legacy_sn" TYPE character varying(2) COLLATE "default",
          ALTER COLUMN "legacy_date_r_raw" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "legacy_date_e_raw" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "legacy_factor_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "legacy_factor" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "legacy_d_dwgok" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "drawing_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "customer_model" TYPE character varying(40) COLLATE "default",
          ALTER COLUMN "material" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "thickness" TYPE character varying(4) COLLATE "default",
          ALTER COLUMN "outsource" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "source" TYPE character varying(4) COLLATE "default",
          ALTER COLUMN "post_process" TYPE character varying(50) COLLATE "default",
          ALTER COLUMN "unit" TYPE character varying(4) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."partners"
          ALTER COLUMN "kind" TYPE character varying(8) COLLATE "default",
          ALTER COLUMN "code" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "full_name" TYPE character varying(100) COLLATE "default",
          ALTER COLUMN "short_name" TYPE character varying(50) COLLATE "default",
          ALTER COLUMN "responsible" TYPE character varying(50) COLLATE "default",
          ALTER COLUMN "phone1" TYPE character varying(40) COLLATE "default",
          ALTER COLUMN "phone2" TYPE character varying(40) COLLATE "default",
          ALTER COLUMN "fax" TYPE character varying(40) COLLATE "default",
          ALTER COLUMN "tax_id" TYPE character varying(30) COLLATE "default",
          ALTER COLUMN "postal_code" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "address" TYPE character varying(250) COLLATE "default",
          ALTER COLUMN "shipping_address" TYPE character varying(250) COLLATE "default",
          ALTER COLUMN "invoice_title" TYPE character varying(100) COLLATE "default",
          ALTER COLUMN "invoice_tax_id" TYPE character varying(30) COLLATE "default",
          ALTER COLUMN "bank_name" TYPE character varying(100) COLLATE "default",
          ALTER COLUMN "bank_account" TYPE character varying(100) COLLATE "default",
          ALTER COLUMN "contact1" TYPE character varying(50) COLLATE "default",
          ALTER COLUMN "contact2" TYPE character varying(50) COLLATE "default",
          ALTER COLUMN "contact3" TYPE character varying(50) COLLATE "default",
          ALTER COLUMN "start_date_raw" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "latest_transaction_date_raw" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "email" TYPE character varying(150) COLLATE "default",
          ALTER COLUMN "dxf_path" TYPE character varying(250) COLLATE "default",
          ALTER COLUMN "main_product" TYPE character varying(100) COLLATE "default",
          ALTER COLUMN "notes" TYPE character varying(2000) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."parts"
          ALTER COLUMN "drawing_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "drawing_name" TYPE character varying(30) COLLATE "default",
          ALTER COLUMN "drawing_ref" TYPE character varying(40) COLLATE "default",
          ALTER COLUMN "customer_code" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "customer_model" TYPE character varying(40) COLLATE "default",
          ALTER COLUMN "material" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "thickness" TYPE character varying(4) COLLATE "default",
          ALTER COLUMN "unit" TYPE character varying(2) COLLATE "default",
          ALTER COLUMN "actor_no" TYPE character varying(6) COLLATE "default",
          ALTER COLUMN "actor" TYPE character varying(8) COLLATE "default",
          ALTER COLUMN "drawing_date_raw" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "directory_path" TYPE character varying(50) COLLATE "default",
          ALTER COLUMN "cnc1" TYPE character varying(30) COLLATE "default",
          ALTER COLUMN "cnc2" TYPE character varying(30) COLLATE "default",
          ALTER COLUMN "cnc3" TYPE character varying(12) COLLATE "default",
          ALTER COLUMN "cnc4" TYPE character varying(12) COLLATE "default",
          ALTER COLUMN "cnc5" TYPE character varying(50) COLLATE "default",
          ALTER COLUMN "notes" TYPE character varying(50) COLLATE "default",
          ALTER COLUMN "yy" TYPE character varying(1) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."phrases"
          ALTER COLUMN "phrase_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "content" TYPE character varying(250) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."postal_codes"
          ALTER COLUMN "postal_code" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "region_name" TYPE character varying(100) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."quote_documents"
          ALTER COLUMN "quote_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "quote_date_raw" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "customer_code" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "customer_name" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "actor_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "actor_name" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "attention" TYPE character varying(40) COLLATE "default",
          ALTER COLUMN "legacy_xx" TYPE character varying(1) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."quote_items"
          ALTER COLUMN "quote_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "customer_model" TYPE character varying(40) COLLATE "default",
          ALTER COLUMN "material" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "thickness" TYPE character varying(6) COLLATE "default",
          ALTER COLUMN "summary" TYPE character varying(250) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."quote_note_lines"
          ALTER COLUMN "quote_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "note" TYPE character varying(250) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."receipt_allocation_lines"
          ALTER COLUMN "receipt_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "sale_no" TYPE character varying(10) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."receipt_documents"
          ALTER COLUMN "receipt_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "receipt_date_raw" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "closing_date_raw" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "customer_code" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "customer_name" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "actor_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "actor_name" TYPE character varying(10) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."receipt_payment_lines"
          ALTER COLUMN "receipt_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "category" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "check_number" TYPE character varying(30) COLLATE "default",
          ALTER COLUMN "check_date_raw" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "bank_account" TYPE character varying(30) COLLATE "default",
          ALTER COLUMN "collect_agent" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "bank_short_name" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "note" TYPE character varying(40) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."sales_documents"
          ALTER COLUMN "sale_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "sale_date_raw" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "legacy_date_e_raw" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "customer_code" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "customer_name" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "actor_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "actor_name" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "linked_order_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "payment_method" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "delivery_method" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "invoice_number" TYPE character varying(30) COLLATE "default",
          ALTER COLUMN "shipping_address" TYPE character varying(60) COLLATE "default",
          ALTER COLUMN "note" TYPE character varying(50) COLLATE "default",
          ALTER COLUMN "tax_mode" TYPE character varying(10) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."sales_items"
          ALTER COLUMN "sale_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "legacy_sn" TYPE character varying(2) COLLATE "default",
          ALTER COLUMN "legacy_date_r_raw" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "legacy_factor_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "legacy_factor" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "drawing_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "customer_model" TYPE character varying(40) COLLATE "default",
          ALTER COLUMN "material" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "thickness" TYPE character varying(6) COLLATE "default",
          ALTER COLUMN "outsource" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "unit" TYPE character varying(4) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."work_documents"
          ALTER COLUMN "work_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "transfer_date_raw" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "customer_code" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "customer_name" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "actor_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "actor_name" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "order_no" TYPE character varying(10) COLLATE "default"`,
    `ALTER TABLE "legacy_crm"."work_items"
          ALTER COLUMN "work_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "drawing_no" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "material" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "thickness" TYPE character varying(6) COLLATE "default",
          ALTER COLUMN "outsource" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "cnc_ok" TYPE character varying(10) COLLATE "default",
          ALTER COLUMN "plating_work" TYPE character varying(20) COLLATE "default",
          ALTER COLUMN "post_process" TYPE character varying(50) COLLATE "default",
          ALTER COLUMN "order_no" TYPE character varying(10) COLLATE "default"`,
  ];

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of this.collate) await queryRunner.query(sql);
    await queryRunner.query(
      `INSERT INTO "features" ("name", "description") VALUES ('crm', '舊版銷管（legacy CRM）：read 可查詢、瀏覽、列印；write 可新增、修改、刪除')
       ON CONFLICT ("name") DO NOTHING`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // crm 功能可能已授權給使用者（user_features），不在 down 刪除。
    for (const sql of this.restore) await queryRunner.query(sql);
  }
}
