import * as fs from 'fs';
import * as path from 'path';
import { Logger } from '@nestjs/common';
import { Repository } from 'typeorm';
import { AttendRecordMapper } from '../attend-record/attend-record-mapper';
import { AttendRecord } from '../attend-record/entities/attend-record.entity';
import { Staff } from '../staff/entities/staff.entity';
import { StaffManhour } from '../staff-manhour/entities/staff-manhour.entity';
import { ManHourManager } from './man-hour-manager';
import { WorkingHours } from './working-hours';

type ExpectedRecord = {
  id: string;
  staffId: string;
  staffName: string;
  createTime: string;
  inputType: string;
  attendType: number;
};
type ExpectedManhour = {
  name: string;
  day: string;
  startTime: string;
  endTime: string | null;
  workTime: number;
};
type Fixture = {
  sourceFileCount: number;
  sourceRowCount: number;
  staff: Array<{ id: string; name: string }>;
  rows: string[][];
  records: ExpectedRecord[];
  manhours: ExpectedManhour[];
};

const fixture: Fixture = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'legacy-attendance.json'), 'utf8'),
);

// The fixture was generated by legacy-attendance-oracle.py using isin_django's
// actual mapper and scheduling methods. Every source employee is treated as
// active because the historical staff table is not part of the raw files.
describe('September 2026 attendance parity with isin_django', () => {
  let actualRecords: ExpectedRecord[];
  let actualManhours: ExpectedManhour[];

  beforeAll(async () => {
    jest.spyOn(Logger.prototype, 'debug').mockImplementation();
    jest.spyOn(Logger.prototype, 'log').mockImplementation();
    jest.spyOn(Logger.prototype, 'warn').mockImplementation();
    const records = new Map<string, AttendRecord>();
    const manhours: StaffManhour[] = [];
    const names = [...new Set(fixture.rows.map((row) => row[2]))];
    const staff = new Map(fixture.staff.map((row) => [row.name, row]));
    const staffRepository = {
      findOne: jest.fn(
        async ({ where }: { where: Partial<Staff> }) =>
          [...staff.values()].find((item) =>
            where.id ? item.id === where.id : item.name === where.name,
          ) || null,
      ),
      createQueryBuilder: jest.fn(() => ({
        select: jest.fn().mockReturnThis(),
        where: jest.fn().mockReturnThis(),
        andWhere: jest.fn().mockReturnThis(),
        getRawMany: jest.fn(async () =>
          names.map((name) => ({ staff_name: name })),
        ),
      })),
    } as unknown as Repository<Staff>;
    const attendRecordRepository = {
      find: jest.fn(async () =>
        [...records.values()]
          .filter((record) => record.attendType === 0)
          .sort((a, b) => a.createTime.getTime() - b.createTime.getTime()),
      ),
      save: jest.fn(async (record: AttendRecord) => {
        records.set(record.id, record);
        return record;
      }),
      createQueryBuilder: jest.fn(() => {
        const params: Record<string, unknown> = {};
        let identityColumn: 'staffId' | 'staffName' = 'staffId';
        const builder = {
          where: jest.fn((_query: string, values: Record<string, unknown>) => {
            Object.assign(params, values);
            return builder;
          }),
          andWhere: jest.fn(
            (_query: string, values: Record<string, unknown>) => {
              Object.assign(params, values);
              if (_query.includes('staffName')) identityColumn = 'staffName';
              return builder;
            },
          ),
          orderBy: jest.fn(() => builder),
          getMany: jest.fn(async () =>
            [...records.values()]
              .filter(
                (record) =>
                  record.createTime >= (params.startTime as Date) &&
                  record.createTime < (params.endTime as Date) &&
                  record[identityColumn] === params.identifier &&
                  (params.attendType === undefined ||
                    record.attendType === params.attendType),
              )
              .sort((a, b) => a.createTime.getTime() - b.createTime.getTime()),
          ),
        };
        return builder;
      }),
    } as unknown as Repository<AttendRecord>;
    const manhourRepository = {
      create: jest.fn(
        (values: Partial<StaffManhour>) =>
          ({
            ...values,
            work_time: 0,
          }) as StaffManhour,
      ),
      save: jest.fn(async (manhour: StaffManhour) => {
        manhour.id = manhours.length + 1;
        manhours.push(manhour);
        return manhour;
      }),
      delete: jest.fn(async ({ name, day }: { name: string; day: Date }) => {
        const oldLength = manhours.length;
        for (let index = manhours.length - 1; index >= 0; index--) {
          if (
            manhours[index].name === name &&
            manhours[index].day?.toISOString() === day.toISOString()
          ) {
            manhours.splice(index, 1);
          }
        }
        return { affected: oldLength - manhours.length };
      }),
    } as unknown as Repository<StaffManhour>;

    const mapper = new AttendRecordMapper(staffRepository);
    for (const row of fixture.rows) {
      const record = mapper.csvToEntity(row);
      expect(mapper.validateAttendRecord(record)).toBe(true);
      // Django's primary key makes a repeated punch idempotent.
      if (!records.has(record.id)) records.set(record.id, record);
    }

    const workingHours = new WorkingHours(
      attendRecordRepository,
      staffRepository,
    );
    await workingHours.appointAttendRecordsType();

    actualRecords = [...records.values()]
      .map((record) => ({
        id: record.id,
        staffId: record.staffId,
        staffName: record.staffName || '',
        createTime: record.createTime.toISOString().replace('.000Z', 'Z'),
        inputType: record.inputType ?? '<missing>',
        attendType: record.attendType,
      }))
      .sort((a, b) => a.id.localeCompare(b.id, 'en'));
    const manager = new ManHourManager(
      manhourRepository,
      staffRepository,
      workingHours,
    );
    const days = [
      ...new Set(
        fixture.records.map((record) => record.createTime.slice(0, 10)),
      ),
    ].sort();
    for (const day of days)
      await manager.calculateManHour(new Date(`${day}T06:00:00Z`));

    actualManhours = manhours
      .map((manhour) => ({
        name: manhour.name,
        day: manhour.day!.toISOString().slice(0, 10),
        startTime: manhour.start_time!.toISOString().replace('.000Z', 'Z'),
        endTime: manhour.end_time?.toISOString().replace('.000Z', 'Z') || null,
        workTime: manhour.work_time,
      }))
      .sort(
        (a, b) =>
          a.day.localeCompare(b.day) ||
          a.name.localeCompare(b.name, 'en') ||
          a.startTime.localeCompare(b.startTime),
      );
  });

  afterAll(() => jest.restoreAllMocks());

  it('matches all 410 mapped punches and their on/off classification', () => {
    expect(fixture.sourceFileCount).toBe(15);
    expect(fixture.sourceRowCount).toBe(410);
    expect(actualRecords).toHaveLength(fixture.records.length);
    actualRecords.forEach((record, index) =>
      expect(record).toEqual(fixture.records[index]),
    );
  });

  it('matches every manhour date and clock-in/clock-out time', () => {
    expect(actualManhours).toHaveLength(fixture.manhours.length);
    actualManhours.forEach((row, index) => {
      const { workTime: _actualWorkTime, ...actualTimes } = row;
      const { workTime: _legacyWorkTime, ...legacyTimes } =
        fixture.manhours[index];
      expect(actualTimes).toEqual(legacyTimes);
    });
  });

  it('matches the legacy manhour work_time value', () => {
    actualManhours.forEach((row, index) =>
      expect(row.workTime).toBe(fixture.manhours[index].workTime),
    );
  });
});
